### ISSUE TITLE
Add Directed Power Management Framework (DFx) handling code to WDF sources

### ISSUE THREAD

**Issue by ghost** [microsoft/Windows-Driver-Frameworks#11]
Please add DFx handling code to the WDF sources.
https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/introduction-to-the-directed-power-management-framework
Thanks.

**Comment by wm1** [comment]
Published in win-10.0.18362.1

**Comment by wm1** [comment]
Refer to [DFx - requirement for WDF driver](https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/introduction-to-the-directed-power-management-framework#requirements-for-wdf-non-miniport-drivers) on how to use DFx in WDF driver. Basically there are 3 steps.
 - The driver uses system managed idle type (instead of the default one, which is driver managed idle)
 - Run on Windows 10 version 1903 or later
 - The driver opt-in to DFx using an INF file key.
